import { useContext, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import ProductContext from '../../context/ProductContext';
import { supabase } from '../../lib/supabase';

const empty={name:'',price:'',category:'Phones',description:'',image:''};
const menu=[['products','fa-box','Products'],['orders','fa-receipt','Orders'],['customers','fa-users','Customers'],['categories','fa-layer-group','Categories'],['users','fa-user-shield','Users']];
const titles={products:'Products',orders:'Orders',customers:'Customers',categories:'Categories',users:'Users'};
const money=value=>`$${Number(value||0).toFixed(2)}`;
const AdminDashboard=()=>{
 const {products,addProduct,updateProduct,deleteProduct}=useContext(ProductContext);
 const navigate=useNavigate(); const [form,setForm]=useState(empty),[editing,setEditing]=useState(null),[view,setView]=useState('products');
 const [checking,setChecking]=useState(true),[orders,setOrders]=useState([]),[users,setUsers]=useState([]),[search,setSearch]=useState(''),[message,setMessage]=useState('');
 const loadAdminData=async()=>{const[{data:orderData,error:orderError},{data:userData,error:userError}]=await Promise.all([supabase.from('orders').select('*, order_items(*)').order('created_at',{ascending:false}),supabase.from('profiles').select('id, full_name, role, created_at').order('created_at',{ascending:false})]);if(orderError||userError)setMessage(orderError?.message||userError?.message);setOrders(orderData||[]);setUsers(userData||[])};
 useEffect(()=>{if(!supabase){navigate('/admin/login');return}supabase.auth.getUser().then(async({data})=>{if(!data.user){navigate('/admin/login');return}const{data:profile}=await supabase.from('profiles').select('role').eq('id',data.user.id).single();if(profile?.role!=='admin'){await supabase.auth.signOut();navigate('/admin/login');return}await loadAdminData();setChecking(false)})},[navigate]);
 const customers=useMemo(()=>Object.values(orders.reduce((map,o)=>{const key=o.email.toLowerCase();if(!map[key])map[key]={name:o.customer_name,email:o.email,phone:o.phone,address:o.address,orders:0,total:0,last:o.created_at};map[key].orders++;map[key].total+=Number(o.total);if(new Date(o.created_at)>new Date(map[key].last))map[key].last=o.created_at;return map},{})),[orders]);
 const categories=useMemo(()=>Object.values(products.reduce((map,p)=>{const key=p.category||'Uncategorized';if(!map[key])map[key]={name:key,count:0,value:0};map[key].count++;map[key].value+=Number(p.price);return map},{})),[products]);
 const q=search.toLowerCase(), visibleProducts=products.filter(p=>`${p.name} ${p.category}`.toLowerCase().includes(q)), visibleOrders=orders.filter(o=>`${o.customer_name} ${o.email} ${o.status} ${o.id}`.toLowerCase().includes(q)), visibleCustomers=customers.filter(c=>`${c.name} ${c.email} ${c.phone}`.toLowerCase().includes(q)), visibleUsers=users.filter(u=>`${u.full_name} ${u.role}`.toLowerCase().includes(q));
 const edit=p=>{setEditing(p.id);setForm(p);window.scrollTo({top:0,behavior:'smooth'})};
 const submit=async e=>{e.preventDefault();setMessage('');try{const product={...form,price:Number(form.price),image:form.image||''};editing?await updateProduct(product):await addProduct(product);setEditing(null);setForm(empty);setMessage('Product saved successfully.')}catch(error){setMessage(error?.message||'Could not save product.')}};
 const remove=async p=>{if(!window.confirm(`Delete ${p.name}?`))return;try{await deleteProduct(p.id);setMessage('Product deleted.')}catch(error){setMessage(error?.message||'Could not delete product.')}};
 const updateStatus=async(id,status)=>{const{error}=await supabase.from('orders').update({status}).eq('id',id);if(error){setMessage(error.message);return}setOrders(items=>items.map(o=>o.id===id?{...o,status}:o));setMessage('Order status updated.')};
 const logout=async()=>{await supabase.auth.signOut();navigate('/admin/login')};
 if(checking)return <div className="auth-page"><div className="empty-state">Checking secure session…</div></div>;
 const table=()=>{
  if(view==='products')return <><form className="product-form" onSubmit={submit}><div><h2>{editing?'Edit product':'Add new product'}</h2><p>Keep your storefront catalog current.</p></div><input placeholder="Product name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input type="number" min="0" step="0.01" placeholder="Price" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} required/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['Phones','Computers','Audio','Gaming','Cameras','TV & Home','Wearables'].map(c=><option key={c}>{c}</option>)}</select><input placeholder="Image URL (optional)" value={typeof form.image==='string'?form.image:''} onChange={e=>setForm({...form,image:e.target.value})}/><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/><div className="form-actions">{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}<button className="button primary">{editing?'Save changes':'Add product'}</button></div></form><AdminTable heads={['Product','Category','Price','Actions']}>{visibleProducts.map(p=><tr key={p.id}><td className="product-cell"><img src={p.image} alt=""/><b>{p.name}</b></td><td><span className="table-tag">{p.category}</span></td><td>{money(p.price)}</td><td><button className="icon-action" onClick={()=>edit(p)}><i className="fa-solid fa-pen"/></button><button className="icon-action delete" onClick={()=>remove(p)}><i className="fa-solid fa-trash"/></button></td></tr>)}</AdminTable></>;
  if(view==='orders')return <AdminTable heads={['Order','Customer','Items','Total','Date','Status']}>{visibleOrders.map(o=><tr key={o.id}><td><b>#{o.id.slice(0,8).toUpperCase()}</b></td><td><b>{o.customer_name}</b><small className="cell-subtitle">{o.email}</small></td><td>{o.order_items?.reduce((s,i)=>s+i.quantity,0)||0}</td><td><b>{money(o.total)}</b></td><td>{new Date(o.created_at).toLocaleDateString()}</td><td><select className={`status-select status-${o.status}`} value={o.status} onChange={e=>updateStatus(o.id,e.target.value)}>{['pending','confirmed','shipped','delivered','cancelled'].map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</AdminTable>;
  if(view==='customers')return <AdminTable heads={['Customer','Contact','Address','Orders','Total spent','Last order']}>{visibleCustomers.map(c=><tr key={c.email}><td><b>{c.name}</b></td><td>{c.email}<small className="cell-subtitle">{c.phone||'No phone'}</small></td><td>{c.address}</td><td>{c.orders}</td><td><b>{money(c.total)}</b></td><td>{new Date(c.last).toLocaleDateString()}</td></tr>)}</AdminTable>;
  if(view==='categories')return <AdminTable heads={['Category','Products','Catalog value']}>{categories.map(c=><tr key={c.name}><td><span className="category-icon"><i className="fa-solid fa-layer-group"/></span><b>{c.name}</b></td><td>{c.count}</td><td>{money(c.value)}</td></tr>)}</AdminTable>;
  return <AdminTable heads={['User','Role','Joined']}>{visibleUsers.map(u=><tr key={u.id}><td><span className="user-avatar">{(u.full_name||'U')[0]}</span><b>{u.full_name||'Unnamed user'}</b></td><td><span className="table-tag">{u.role}</span></td><td>{new Date(u.created_at).toLocaleDateString()}</td></tr>)}</AdminTable>;
 };
 return <div className="admin-layout"><aside><div className="brand"><span className="brand-mark"><i className="fa-solid fa-bolt"/></span><span>Volt<span>X</span></span></div><nav>{menu.map(([key,icon,label])=><button key={key} className={view===key?'active':''} onClick={()=>{setView(key);setSearch('')}}><i className={`fa-solid ${icon}`}/>{label}<small>{key==='products'?products.length:key==='orders'?orders.length:key==='customers'?customers.length:key==='categories'?categories.length:users.length}</small></button>)}</nav><button className="admin-logout" onClick={logout}><i className="fa-solid fa-arrow-right-from-bracket"/>Log out</button></aside><section className="admin-main"><header><div><p>STORE MANAGEMENT</p><h1>{titles[view]}</h1></div><span className="admin-user"><i className="fa-solid fa-user-shield"/>Administrator</span></header><div className="admin-stats four"><Stat icon="fa-boxes-stacked" label="Products" value={products.length}/><Stat icon="fa-receipt" label="Orders" value={orders.length}/><Stat icon="fa-users" label="Customers" value={customers.length}/><Stat icon="fa-dollar-sign" label="Revenue" value={money(orders.filter(o=>o.status!=='cancelled').reduce((s,o)=>s+Number(o.total),0))}/></div>{message&&<div className={message.includes('success')||message.includes('updated')||message.includes('deleted')?'admin-notice success':'admin-notice'}>{message}</div>}<div className="admin-toolbar"><label><i className="fa-solid fa-magnifying-glass"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${titles[view].toLowerCase()}...`}/></label><button onClick={loadAdminData}><i className="fa-solid fa-rotate"/>Refresh</button></div>{table()}</section></div>;
};
const Stat=({icon,label,value})=><div><i className={`fa-solid ${icon}`}/><span><small>{label}</small><b>{value}</b></span></div>;
const AdminTable=({heads,children})=><div className="admin-table-wrap"><table className="admin-table"><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table>{!children.length&&<div className="empty-state"><i className="fa-solid fa-table-list"/><h3>No records found</h3></div>}</div>;
export default AdminDashboard;
